SOURCE_NAME = "gitlab"
DEFAULT_INSTANCE_ID = ""

# Access levels
ACCESS_LEVEL_GUEST = 10
ACCESS_LEVEL_REPORTER = 20
ACCESS_LEVEL_DEVELOPER = 30
ACCESS_LEVEL_MAINTAINER = 40
ACCESS_LEVEL_OWNER = 50

# Sheet Names
SHEET_NAME_USERS = "Gitlab Users"
SHEET_NAME_GROUPS = "Gitlab Groups"
SHEET_NAME_PROJECTS = "Gitlab Projects"

# Roles Mapping
ROLES_MAP = {
    ACCESS_LEVEL_GUEST: "Guest",
    ACCESS_LEVEL_REPORTER: "Reporter",
    ACCESS_LEVEL_DEVELOPER: "Developer",
    ACCESS_LEVEL_MAINTAINER: "Maintainer",
    ACCESS_LEVEL_OWNER: "Owner",
}
